name: Build and Deploy Firmware

on:
  push:
    branches: [ main ] # S'exécute quand tu modifies le code sur la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 Platform
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Install Libraries
        run: |
          arduino-cli lib install "ESP32 HUB75 LED MATRIX PANEL DMA Display"
          arduino-cli lib install "Adafruit GFX Library"

      - name: Compile Sketch
        run: |
          # On compile le fichier .ino et on place le résultat dans le dossier ./build
          arduino-cli compile --fqbn esp32:esp32:esp32 --output-dir ./build ./murmuration_poetique.ino

      - name: Deploy Binary to Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build-bin # C'est ici que l'ESP32 ira chercher le fichier
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Auto-build firmware: {sha}"
