name: Build and Deploy Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 Platform (Version Stable)
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          # On installe la version 2.0.17, beaucoup plus stable pour les panneaux HUB75
          arduino-cli core install esp32:esp32@2.0.17 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Install Libraries
        run: |
          # Installation forcée des bibliothèques dans l'ordre
          arduino-cli lib install "Adafruit GFX Library"
          arduino-cli lib install "Adafruit BusIO"
          arduino-cli lib install "FastLED"
          arduino-cli lib install "ESP32 HUB75 LED MATRIX PANEL DMA Display"

      - name: Compile Sketch with Secrets
        run: |
          mkdir -p build
          # On compile le fichier starlings-box.ino avec tes secrets
          arduino-cli compile --fqbn esp32:esp32:esp32 \
            --build-property "build.extra_flags=-DWIFI_SSID=\"${{ secrets.WIFI_SSID }}\" -DWIFI_PASS=\"${{ secrets.WIFI_PASS }}\"" \
            --output-dir ./build ./starlings-box.ino

      - name: Deploy Binary to Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build-bin
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Auto-build firmware: {sha}"
